#+title: Devlog: Vibrato Weekly Accomplishments

This file tracks the weekly development progress on Vibrato Notes - new features, bug fixes, and more.

* December 9 - December 15
** Added various tag operations (add tag, delete tag, rename tag)
** Created a 'Manager' class to hold all of the UI Managers. This makes it easy to access each of the UI Manager instances in all of the UI Manager classes.
** Improved the ux of the 'New Note' feature.
** Made the notelist sidebar properly refresh when a notebook is renamed.
** Fixed bug where imported notebooks in 'Default Notebook' weren't properly set.
* December 16 - December 22
** Added a 'trash note' functionality!
** Polished tagging functions
** Added "favorite note" functionality!
** Added solid yellow star icon to indicate favorited notes (resources/icons/vibrato-default/icons/vibrato-draw-star-solid.svg)
** Added "favorite note" icon to the Escriba text editor toolbar
** Made favorites view update when you un-favorite a note
** Added "trashed" property to Note class
** Updated the Note class to utilize the updateModifiedDate boolean
